import { useCallback, useEffect, useMemo, useState } from "react";
import type { CategorySummary, CitizenTicketSummary } from "@civicos/shared";
import * as ImagePicker from "expo-image-picker";
import * as Location from "expo-location";
import MapView, { Marker } from "react-native-maps";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { LocalImage } from "./api";
import { AppIcon, Card, CategoryGrid, PrimaryButton, ScreenHeader, SecondaryButton, StatusChip } from "./components";
import { Shell } from "./screen-shell";
import { colors, fontWeights, radii } from "./theme";

const reportSteps = ["Category", "Photo", "Detect", "Confirm", "Review", "Submit"];

function ReportProgress({ step }: { step: number }) {
  return <View accessibilityLabel={`Report step ${step} of ${reportSteps.length}`} style={styles.progressWrap}><View style={styles.progressTop}><Text style={styles.progressText}>Step {step} of {reportSteps.length}</Text><Text style={styles.progressLabel}>{reportSteps[step - 1]}</Text></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${(step / reportSteps.length) * 100}%` }]} /></View></View>;
}

export function CategoryScreen({ categories, selectedId, onSelect, onBack, loading, error }: { categories: CategorySummary[]; selectedId?: string; onSelect: (category: CategorySummary) => void; onBack: () => void; loading: boolean; error?: string }) {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => categories.filter((category) => category.name.toLowerCase().includes(query.toLowerCase())), [categories, query]);
  return <Shell><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="What needs attention?" subtitle="Choose the category that best matches the issue." onBack={onBack} /><ReportProgress step={1} /><View style={styles.search}><AppIcon color={colors.muted} name="search-outline" size={19} /><TextInput accessibilityLabel="Search issue categories" onChangeText={setQuery} placeholder="Search issue types" placeholderTextColor={colors.muted} style={styles.searchInput} value={query} /></View>{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<CategoryGrid categories={filtered} selectedId={selectedId} onSelect={onSelect} /></ScrollView></Shell>;
}

export function normalizeAsset(asset: ImagePicker.ImagePickerAsset): LocalImage {
  const extension = asset.uri.split(".").pop()?.toLowerCase();
  const contentType = asset.mimeType === "image/png" || extension === "png" ? "image/png" : asset.mimeType === "image/webp" || extension === "webp" ? "image/webp" : asset.mimeType === "image/heic" || extension === "heic" ? "image/heic" : "image/jpeg";
  return { uri: asset.uri, fileName: asset.fileName ?? `city-connect-${Date.now()}.${extension ?? "jpg"}`, contentType };
}

export function EvidenceScreen({ images, onChange, onNext, onBack }: { images: LocalImage[]; onChange: (images: LocalImage[]) => void; onNext: () => void; onBack: () => void }) {
  const pick = async (source: "camera" | "gallery") => {
    const permission = source === "camera" ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) return;
    const result = source === "camera" ? await ImagePicker.launchCameraAsync({ mediaTypes: ["images"], quality: 0.85, exif: true }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.85, allowsMultipleSelection: true, selectionLimit: Math.max(1, 4 - images.length), exif: true });
    if (!result.canceled) onChange([...images, ...result.assets.map(normalizeAsset)].slice(0, 4));
  };
  const remove = (index: number) => onChange(images.filter((_image, imageIndex) => imageIndex !== index));
  return <Shell><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="Show us the issue" subtitle="A clear photo helps the right team understand the problem." onBack={onBack} /><ReportProgress step={2} /><Pressable accessibilityRole="button" onPress={() => void pick(images[0] ? "gallery" : "camera")} style={[styles.photoTile, styles.primaryPhoto]}>{images[0] ? <><Image source={{ uri: images[0].uri }} style={styles.photo} /><View style={styles.photoOverlay}><Text style={styles.photoOverlayText}>Primary evidence</Text></View></> : <View style={styles.photoPrompt}><View style={styles.cameraCircle}><AppIcon color={colors.primary} name="camera" size={29} /></View><Text style={styles.photoTitle}>Add a clear main photo</Text><Text style={styles.photoHint}>Make sure the civic issue is visible</Text></View>}</Pressable><View style={styles.photoActions}><SecondaryButton icon="camera-outline" onPress={() => void pick("camera")}>Camera</SecondaryButton><SecondaryButton icon="images-outline" onPress={() => void pick("gallery")}>Gallery</SecondaryButton></View>{images.length ? <View style={styles.thumbnailRow}>{images.map((image, index) => <View key={`${image.uri}-${index}`} style={styles.thumbnail}><Image source={{ uri: image.uri }} style={styles.photo} /><Pressable accessibilityLabel={`Remove photo ${index + 1}`} onPress={() => remove(index)} style={styles.removePhoto}><AppIcon color={colors.surface} name="close" size={14} /></Pressable></View>)}{images.length < 4 ? <Pressable onPress={() => void pick("gallery")} style={styles.addTile}><AppIcon color={colors.primary} name="add" size={25} /></Pressable> : null}</View> : null}<Text style={styles.helper}><AppIcon color={colors.muted} name="shield-checkmark-outline" size={15} /> Up to 4 photos. Your evidence is stored securely.</Text><PrimaryButton disabled={!images[0]} icon="arrow-forward" onPress={onNext}>Continue to location</PrimaryButton></ScrollView></Shell>;
}

export type ConfirmedLocation = { latitude: number; longitude: number; address: string; confidenceLow: boolean };

async function detectCurrentLocation(): Promise<ConfirmedLocation> {
  const permission = await Location.requestForegroundPermissionsAsync();
  if (!permission.granted) throw new Error("Location permission is needed to route your report. Enable it and try again.");
  const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High });
  const { latitude, longitude, accuracy } = position.coords;
  const places = await Location.reverseGeocodeAsync({ latitude, longitude });
  const place = places[0];
  const address = place ? [place.name, place.street, place.district, place.city, place.region].filter(Boolean).join(", ") : `${latitude.toFixed(5)}, ${longitude.toFixed(5)}`;
  return { latitude, longitude, address, confidenceLow: (accuracy ?? 100) > 40 };
}

export function LocationDetectScreen({ onDetected, onBack }: { onDetected: (location: ConfirmedLocation) => void; onBack: () => void }) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>();
  const detect = useCallback(async () => {
    setLoading(true); setError(undefined);
    try { onDetected(await detectCurrentLocation()); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn’t detect your location. Please try again."); }
    finally { setLoading(false); }
  }, [onDetected]);
  useEffect(() => { void detect(); }, [detect]);
  return <Shell><View style={[styles.content, styles.detectContent]}><ScreenHeader title="Detecting your location" subtitle="City Connect uses your location to identify the ward and responsible agency." onBack={onBack} /><ReportProgress step={3} /><View style={styles.locationVisual}><View style={styles.locationPulse}><AppIcon color={colors.surface} name="locate" size={36} /></View><View style={styles.locationRing} /></View>{loading ? <View style={styles.detectStatus}><ActivityIndicator color={colors.primary} /><Text style={styles.body}>Finding your current GPS position…</Text></View> : null}{error ? <Card style={styles.errorCard}><AppIcon color={colors.danger} name="location-outline" size={24} /><Text style={styles.errorTitle}>Location unavailable</Text><Text style={styles.error}>{error}</Text><PrimaryButton icon="refresh" onPress={() => void detect()}>Try again</PrimaryButton></Card> : null}</View></Shell>;
}

export function LocationConfirmScreen({ value, onChange, onNext, onRetry, onBack }: { value: ConfirmedLocation; onChange: (location: ConfirmedLocation) => void; onNext: () => void; onRetry: () => void; onBack: () => void }) {
  const [adjusting, setAdjusting] = useState(false);
  const movePin = (event: { nativeEvent: { coordinate: { latitude: number; longitude: number } } }) => onChange({ ...value, ...event.nativeEvent.coordinate, confidenceLow: false });
  return <Shell><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="Confirm the location" subtitle="Check the pin and address before continuing." onBack={onBack} /><ReportProgress step={4} /><View style={styles.mapWrap}><MapView onPress={adjusting ? movePin : undefined} region={{ latitude: value.latitude, longitude: value.longitude, latitudeDelta: 0.008, longitudeDelta: 0.008 }} style={styles.map}><Marker coordinate={value} draggable onDragEnd={movePin} /></MapView><View pointerEvents="none" style={styles.mapStatus}><AppIcon color={colors.successText} name="checkmark-circle" size={16} /><Text style={styles.mapStatusText}>GPS location detected</Text></View></View><Card><Text style={styles.inputLabel}>Detected address</Text><TextInput accessibilityLabel="Issue address" multiline onChangeText={(address) => onChange({ ...value, address })} style={[styles.input, styles.addressInput]} value={value.address} /><View style={styles.coordinates}><Text style={styles.coordinateText}>{value.latitude.toFixed(5)}, {value.longitude.toFixed(5)}</Text><Pressable onPress={onRetry}><Text style={styles.retryText}>Detect again</Text></Pressable></View></Card>{value.confidenceLow ? <Text style={styles.notice}>The GPS reading may be approximate. Adjust the pin or edit the address.</Text> : null}<SecondaryButton icon="pin-outline" onPress={() => setAdjusting((current) => !current)}>{adjusting ? "Finish adjusting" : "Adjust map pin"}</SecondaryButton><PrimaryButton disabled={!value.address.trim()} icon="arrow-forward" onPress={onNext}>Review report</PrimaryButton></ScrollView></Shell>;
}

export function ReviewReportScreen({ category, image, location, submitting, onBack, onSubmit }: { category: CategorySummary; image: LocalImage; location: ConfirmedLocation; submitting: boolean; onBack: () => void; onSubmit: () => void }) {
  return <Shell><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="Review your report" subtitle="Make sure these details are correct before submitting." onBack={onBack} /><ReportProgress step={5} /><Card style={styles.reviewCard}><Image source={{ uri: image.uri }} style={styles.reviewPhoto} /><View style={styles.reviewSection}><Text style={styles.reviewLabel}>ISSUE CATEGORY</Text><Text style={styles.reviewValue}>{category.name}</Text></View><View style={styles.reviewDivider} /><View style={styles.reviewLocation}><AppIcon color={colors.primary} name="location" size={21} /><View style={styles.reviewCopy}><Text style={styles.reviewLabel}>LOCATION</Text><Text style={styles.reviewValue}>{location.address}</Text><Text style={styles.coordinateText}>{location.latitude.toFixed(5)}, {location.longitude.toFixed(5)}</Text></View></View></Card><View style={styles.submitNotice}><AppIcon color={colors.primary} name="people-outline" size={21} /><Text style={styles.submitNoticeText}>After submission, your report will wait for community validation before reaching the responsible agency.</Text></View><ReportProgress step={6} /><PrimaryButton disabled={submitting} icon="send" onPress={onSubmit}>{submitting ? "Submitting securely…" : "Submit report"}</PrimaryButton></ScrollView></Shell>;
}

export function RetakeScreen({ message, attemptsRemaining, onRetake }: { message: string; attemptsRemaining: number; onRetake: () => void }) {
  return <Shell><View style={[styles.content, styles.centered]}><View style={styles.feedbackIcon}><AppIcon color={colors.warningText} name="camera-reverse-outline" size={38} /></View><ScreenHeader title="Let’s try a clearer photo" subtitle={message} /><Text style={styles.centerHint}>{attemptsRemaining} photo {attemptsRemaining === 1 ? "try" : "tries"} remaining before the report is sent for a person to review.</Text><PrimaryButton icon="camera" onPress={onRetake}>Retake photo</PrimaryButton></View></Shell>;
}

export function ConfirmationScreen({ ticket, image, location, onView, onDone }: { ticket: CitizenTicketSummary; image: LocalImage; location: ConfirmedLocation; onView: () => void; onDone: () => void }) {
  return <Shell><ScrollView contentContainerStyle={[styles.content, styles.confirmation]}><View style={styles.success}><AppIcon color={colors.surface} name="checkmark" size={30} /></View><Text style={styles.successKicker}>REPORT SUBMITTED</Text><Text style={styles.confirmTitle}>We’ve received your report</Text><Text style={styles.centerBody}>You can track every step from your City Connect account.</Text><Card style={styles.confirmCard}><Image source={{ uri: image.uri }} style={styles.confirmPhoto} /><View style={styles.ticketRow}><View><Text style={styles.reviewLabel}>TICKET ID</Text><Text selectable style={styles.ticketNumber}>{ticket.referenceNumber}</Text></View><StatusChip label={ticket.statusLabel} /></View><Text style={styles.reviewValue}>{ticket.category.name}</Text><View style={styles.reviewLocation}><AppIcon color={colors.muted} name="location-outline" size={18} /><Text style={[styles.body, styles.reviewCopy]}>{location.address}</Text></View></Card><View style={styles.nextStep}><View style={styles.nextStepLine} /><View style={styles.nextStepDot}><AppIcon color={colors.surface} name="people" size={18} /></View><View style={styles.reviewCopy}><Text style={styles.reviewLabel}>NEXT EXPECTED STEP</Text><Text style={styles.nextStepTitle}>Waiting for community validation</Text><Text style={styles.photoHint}>Three unique confirmations will move this report to the responsible agency.</Text></View></View><PrimaryButton onPress={onView}>View ticket details</PrimaryButton><SecondaryButton onPress={onDone}>Back to Home</SecondaryButton></ScrollView></Shell>;
}

const styles = StyleSheet.create({
  content: { flexGrow: 1, gap: 18, padding: 20, paddingBottom: 36, paddingTop: 22 }, progressWrap: { gap: 7 }, progressTop: { flexDirection: "row", justifyContent: "space-between" }, progressText: { color: colors.primary, fontSize: 11, fontWeight: fontWeights.bold, textTransform: "uppercase" }, progressLabel: { color: colors.muted, fontSize: 11, fontWeight: fontWeights.semibold }, progressTrack: { backgroundColor: colors.border, borderRadius: 4, height: 5, overflow: "hidden" }, progressFill: { backgroundColor: colors.primary, borderRadius: 4, height: 5 },
  search: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 8, paddingHorizontal: 14 }, searchInput: { color: colors.ink, flex: 1, fontSize: 15, minHeight: 50 }, error: { color: colors.danger, fontSize: 14, lineHeight: 20 },
  photoTile: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.card, borderStyle: "dashed", borderWidth: 2, justifyContent: "center", overflow: "hidden" }, primaryPhoto: { height: 285 }, photo: { height: "100%", width: "100%" }, photoPrompt: { alignItems: "center", gap: 9, padding: 24 }, cameraCircle: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 28, height: 56, justifyContent: "center", width: 56 }, photoTitle: { color: colors.ink, fontSize: 17, fontWeight: fontWeights.semibold }, photoHint: { color: colors.muted, fontSize: 12, lineHeight: 18 }, photoOverlay: { backgroundColor: colors.overlay, borderRadius: 10, bottom: 12, left: 12, paddingHorizontal: 10, paddingVertical: 6, position: "absolute" }, photoOverlayText: { color: colors.surface, fontSize: 11, fontWeight: fontWeights.semibold }, photoActions: { flexDirection: "row", gap: 10 }, thumbnailRow: { flexDirection: "row", gap: 9 }, thumbnail: { borderRadius: 12, height: 70, overflow: "hidden", width: 70 }, removePhoto: { alignItems: "center", backgroundColor: colors.overlay, borderRadius: 11, height: 22, justifyContent: "center", position: "absolute", right: 3, top: 3, width: 22 }, addTile: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 12, height: 70, justifyContent: "center", width: 70 }, helper: { alignItems: "center", color: colors.muted, fontSize: 11, textAlign: "center" },
  detectContent: { justifyContent: "flex-start" }, locationVisual: { alignItems: "center", height: 230, justifyContent: "center" }, locationPulse: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 47, height: 94, justifyContent: "center", width: 94, zIndex: 2 }, locationRing: { borderColor: colors.primarySoft, borderRadius: 82, borderWidth: 18, height: 164, position: "absolute", width: 164 }, detectStatus: { alignItems: "center", gap: 12 }, body: { color: colors.muted, fontSize: 14, lineHeight: 21 }, errorCard: { alignItems: "center", gap: 12 }, errorTitle: { color: colors.ink, fontSize: 17, fontWeight: fontWeights.bold },
  mapWrap: { borderRadius: radii.card, height: 290, overflow: "hidden" }, map: { height: "100%", width: "100%" }, mapStatus: { alignItems: "center", backgroundColor: colors.surface, borderRadius: 15, flexDirection: "row", gap: 5, left: 12, paddingHorizontal: 10, paddingVertical: 7, position: "absolute", top: 12 }, mapStatusText: { color: colors.successText, fontSize: 11, fontWeight: fontWeights.semibold }, inputLabel: { color: colors.ink, fontSize: 12, fontWeight: fontWeights.semibold }, input: { backgroundColor: colors.surfaceAlt, borderColor: colors.border, borderRadius: 13, borderWidth: 1, color: colors.ink, fontSize: 15, paddingHorizontal: 14, paddingVertical: 12 }, addressInput: { minHeight: 74, textAlignVertical: "top" }, coordinates: { flexDirection: "row", justifyContent: "space-between" }, coordinateText: { color: colors.muted, fontSize: 11 }, retryText: { color: colors.primary, fontSize: 12, fontWeight: fontWeights.semibold }, notice: { backgroundColor: colors.warningBg, borderRadius: 14, color: colors.warningText, fontSize: 13, lineHeight: 19, padding: 13 },
  reviewCard: { gap: 14, padding: 0, overflow: "hidden" }, reviewPhoto: { height: 210, width: "100%" }, reviewSection: { gap: 5, paddingHorizontal: 17 }, reviewLabel: { color: colors.muted, fontSize: 10, fontWeight: fontWeights.bold, letterSpacing: 0.8 }, reviewValue: { color: colors.ink, fontSize: 16, fontWeight: fontWeights.semibold, lineHeight: 22 }, reviewDivider: { backgroundColor: colors.border, height: 1, marginHorizontal: 17 }, reviewLocation: { alignItems: "flex-start", flexDirection: "row", gap: 9, paddingBottom: 17, paddingHorizontal: 17 }, reviewCopy: { flex: 1, gap: 4 }, submitNotice: { alignItems: "flex-start", backgroundColor: colors.primarySoft, borderRadius: 15, flexDirection: "row", gap: 10, padding: 14 }, submitNoticeText: { color: colors.successText, flex: 1, fontSize: 13, lineHeight: 19 },
  centered: { justifyContent: "center" }, feedbackIcon: { alignItems: "center", alignSelf: "center", backgroundColor: colors.warningBg, borderRadius: 40, height: 80, justifyContent: "center", width: 80 }, centerHint: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: "center" }, confirmation: { alignItems: "stretch" }, success: { alignItems: "center", alignSelf: "center", backgroundColor: colors.primary, borderRadius: 40, height: 80, justifyContent: "center", width: 80 }, successKicker: { color: colors.primary, fontSize: 11, fontWeight: fontWeights.bold, letterSpacing: 1.1, textAlign: "center" }, confirmTitle: { color: colors.ink, fontSize: 25, fontWeight: fontWeights.bold, textAlign: "center" }, centerBody: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: "center" }, confirmCard: { overflow: "hidden", padding: 0, paddingBottom: 16 }, confirmPhoto: { height: 150, width: "100%" }, ticketRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 17, paddingTop: 14 }, ticketNumber: { color: colors.ink, fontSize: 18, fontWeight: fontWeights.bold, marginTop: 3 }, nextStep: { alignItems: "center", backgroundColor: colors.surface, borderRadius: 18, flexDirection: "row", gap: 12, overflow: "hidden", padding: 16 }, nextStepLine: { backgroundColor: colors.primary, height: "100%", left: 0, position: "absolute", width: 4 }, nextStepDot: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 20, height: 40, justifyContent: "center", width: 40 }, nextStepTitle: { color: colors.ink, fontSize: 15, fontWeight: fontWeights.semibold },
});
