import { useState } from "react";
import { notificationPresentation, relativeNotificationTime } from "@civicos/shared";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { requestCitizenOtp, verifyCitizenOtp, type CurrentAuth, type MobileNotification } from "./api";
import { AppIcon, BrandLockup, Card, NotificationRow, PrimaryButton, ScreenHeader, SecondaryButton } from "./components";
import { Shell } from "./screen-shell";
import { colors, fontWeights, radii, typeScale } from "./theme";

export { Shell } from "./screen-shell";
export * from "./report-screens";
export * from "./ticket-screens";
export * from "./validation-screens";
export * from "./profile-screen";

export function SplashScreen() {
  return <View style={styles.splash}><View style={styles.splashGlow} /><BrandLockup light /><ActivityIndicator color={colors.lime} size="large" /><Text style={styles.splashCopy}>Report. Track. Resolve.</Text></View>;
}

export function WelcomeScreen({ onCitizen, onStaff }: { onCitizen: () => void; onStaff: () => void }) {
  return <Shell><ScrollView contentContainerStyle={styles.welcome}>
    <View style={styles.welcomeTop}><BrandLockup /><View style={styles.welcomeArt}><View style={styles.cityCircle}><AppIcon color={colors.surface} name="business" size={46} /></View><View style={styles.roadLine} /></View></View>
    <View style={styles.welcomeCopy}><Text style={styles.welcomeTitle}>Your city, one tap away.</Text><Text style={styles.welcomeSubtitle}>Report civic issues, follow every update, and help your community move problems toward resolution.</Text></View>
    <View style={styles.welcomeActions}><PrimaryButton icon="phone-portrait-outline" onPress={onCitizen}>Continue as Citizen</PrimaryButton><Pressable accessibilityRole="button" onPress={onStaff} style={styles.staffLink}><AppIcon color={colors.muted} name="shield-checkmark-outline" size={17} /><Text style={styles.staffLinkText}>Staff sign in</Text></Pressable></View>
    <Text style={styles.secureNote}>Secure access · Real ticket tracking · City Connect</Text>
  </ScrollView></Shell>;
}

export function CitizenLoginScreen({ onAuthenticated, onBack }: { onAuthenticated: (auth: CurrentAuth) => void; onBack: () => void }) {
  const [phone, setPhone] = useState("");
  const [code, setCode] = useState("");
  const [step, setStep] = useState<"phone" | "code">("phone");
  const [demoMode, setDemoMode] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();
  const submit = async () => {
    setBusy(true); setError(undefined);
    try {
      if (step === "phone") { const result = await requestCitizenOtp(phone.replaceAll(" ", "")); setDemoMode(result.demoMode); setStep("code"); }
      else onAuthenticated(await verifyCitizenOtp(phone.replaceAll(" ", ""), code));
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not sign in"); }
    finally { setBusy(false); }
  };
  return <Shell><ScrollView contentContainerStyle={styles.authContent}><BrandLockup compact /><ScreenHeader eyebrow={step === "phone" ? "Citizen access" : "Phone verification"} title={step === "phone" ? "Sign in with your phone" : "Enter your 6-digit code"} subtitle={step === "phone" ? "New phone numbers automatically create a secure citizen account." : demoMode ? "Demo mode is active. Enter the rehearsal OTP supplied by the presenter." : `We sent a one-time code to ${phone}.`} onBack={step === "code" ? () => setStep("phone") : onBack} />
    <Card style={styles.authCard}>{step === "phone" ? <><Text style={styles.inputLabel}>Mobile number</Text><TextInput accessibilityLabel="Mobile number" autoComplete="tel" keyboardType="phone-pad" value={phone} onChangeText={setPhone} placeholder="+91 98765 43210" placeholderTextColor={colors.muted} style={styles.input} /></> : <><Text style={styles.inputLabel}>One-time password</Text><TextInput accessibilityLabel="One-time code" autoComplete="one-time-code" keyboardType="number-pad" maxLength={6} value={code} onChangeText={setCode} placeholder="000000" placeholderTextColor={colors.muted} style={[styles.input, styles.otpInput]} /></>}{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={busy || (step === "phone" ? phone.replace(/\D/g, "").length < 10 : code.length !== 6)} onPress={() => void submit()}>{busy ? "Please wait…" : step === "phone" ? "Send OTP" : "Verify and continue"}</PrimaryButton>{step === "code" ? <SecondaryButton disabled={busy} onPress={() => void requestCitizenOtp(phone.replaceAll(" ", ""))}>Send a new code</SecondaryButton> : null}</Card>
    <Text style={styles.privacy}>Your phone number is used only to secure your City Connect account and connect you to your reports.</Text>
  </ScrollView></Shell>;
}

const journey = [
  { label: "Report", icon: "camera-outline" as const },
  { label: "Community\nCheck", icon: "people-outline" as const },
  { label: "Agency", icon: "business-outline" as const },
  { label: "Work", icon: "construct-outline" as const },
  { label: "Verify", icon: "checkmark-circle-outline" as const },
];

export type CitizenHomeSummary = {
  pendingValidations: number;
  pendingCompletions: number;
  ongoingReports: number;
  resolvedReports: number;
  recentNotifications: MobileNotification[];
};

export function HomeScreen({ auth, unread, summary, loading, onReport, onTickets, onValidations, onCompletionValidations, onNotifications, onProfile, onOpenNotification }: {
  auth: CurrentAuth; unread: number; summary: CitizenHomeSummary; loading: boolean; onReport: () => void; onTickets: (filter: "ongoing" | "past") => void; onValidations: () => void; onCompletionValidations: () => void; onNotifications: () => void; onProfile: () => void; onOpenNotification: (notification: MobileNotification) => void;
}) {
  const attention = summary.pendingValidations + summary.pendingCompletions;
  const phoneTail = auth.phone?.slice(-4);
  return <Shell><ScrollView contentContainerStyle={styles.homeContent}>
    <View style={styles.homeHeader}><View><BrandLockup compact /><Text style={styles.greeting}>{phoneTail ? `Welcome back · •••• ${phoneTail}` : "Welcome back"}</Text></View><View style={styles.headerActions}><Pressable accessibilityLabel="Open notifications" accessibilityRole="button" onPress={onNotifications} style={styles.iconButton}><AppIcon color={colors.ink} name="notifications-outline" size={22} />{unread > 0 ? <View style={styles.badge}><Text style={styles.badgeText}>{unread > 9 ? "9+" : unread}</Text></View> : null}</Pressable><Pressable accessibilityLabel="Open profile" accessibilityRole="button" onPress={onProfile} style={styles.avatar}><AppIcon color={colors.primary} name="person" size={20} /></Pressable></View></View>
    <View style={styles.hero}><View style={styles.heroGlow} /><Text style={styles.heroEyebrow}>CITY CONNECT</Text><Text style={styles.heroTitle}>Spot a civic issue?</Text><Text style={styles.heroBody}>Report it with a photo and location. We’ll help take it from report to resolution.</Text><Pressable accessibilityRole="button" onPress={onReport} style={styles.heroButton}><AppIcon color={colors.hero} name="add-circle" size={21} /><Text style={styles.heroButtonText}>Report an Issue</Text><AppIcon color={colors.hero} name="arrow-forward" size={18} /></Pressable></View>
    <View style={styles.journeyCard}><Text style={styles.sectionKicker}>HOW IT WORKS</Text><View style={styles.journey}>{journey.map((item, index) => <View key={item.label} style={styles.journeyItem}><View style={styles.journeyIcon}><AppIcon color={colors.primary} name={item.icon} size={18} /></View><Text style={styles.journeyLabel}>{item.label}</Text>{index < journey.length - 1 ? <View style={styles.journeyLine} /> : null}</View>)}</View></View>
    {loading ? <ActivityIndicator color={colors.primary} /> : null}
    {attention > 0 ? <View style={styles.section}><View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Needs your attention</Text><View style={styles.countChip}><Text style={styles.countChipText}>{attention}</Text></View></View>{summary.pendingCompletions > 0 ? <Pressable onPress={onCompletionValidations} style={styles.attentionCard}><View style={[styles.taskIcon, styles.taskIconWarning]}><AppIcon color={colors.warningText} name="checkmark-done-outline" size={22} /></View><View style={styles.taskCopy}><Text style={styles.taskTitle}>Verify completed work</Text><Text style={styles.taskSubtitle}>{summary.pendingCompletions} resolution {summary.pendingCompletions === 1 ? "check needs" : "checks need"} your response</Text></View><AppIcon color={colors.muted} name="chevron-forward" /></Pressable> : null}{summary.pendingValidations > 0 ? <Pressable onPress={onValidations} style={styles.attentionCard}><View style={styles.taskIcon}><AppIcon color={colors.infoText} name="people-outline" size={22} /></View><View style={styles.taskCopy}><Text style={styles.taskTitle}>Community validation</Text><Text style={styles.taskSubtitle}>{summary.pendingValidations} reported {summary.pendingValidations === 1 ? "issue" : "issues"} to confirm</Text></View><AppIcon color={colors.muted} name="chevron-forward" /></Pressable> : null}</View> : null}
    <View style={styles.section}><View style={styles.sectionHeading}><View><Text style={styles.sectionTitle}>Community validation</Text><Text style={styles.sectionSubtitle}>Help confirm reported civic issues</Text></View></View><Pressable accessibilityRole="button" onPress={onValidations} style={styles.communityCard}><View style={styles.communityIcon}><AppIcon color={colors.surface} name="people" size={26} /></View><View style={styles.taskCopy}><Text style={styles.taskTitle}>Help verify reported issues</Text><Text style={styles.taskSubtitle}>{summary.pendingValidations ? `${summary.pendingValidations} pending requests` : "You’re all caught up"}</Text></View><AppIcon color={colors.primary} name="arrow-forward-circle" size={25} /></Pressable></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>My reports</Text><View style={styles.reportStats}><Pressable onPress={() => onTickets("ongoing")} style={styles.reportStat}><View style={styles.reportStatTop}><AppIcon color={colors.infoText} name="time-outline" size={21} /><Text style={styles.reportCount}>{summary.ongoingReports}</Text></View><Text style={styles.reportLabel}>Ongoing</Text><Text style={styles.reportHint}>Track active work</Text></Pressable><Pressable onPress={() => onTickets("past")} style={styles.reportStat}><View style={styles.reportStatTop}><AppIcon color={colors.successText} name="checkmark-circle-outline" size={21} /><Text style={styles.reportCount}>{summary.resolvedReports}</Text></View><Text style={styles.reportLabel}>Resolved</Text><Text style={styles.reportHint}>View closed reports</Text></Pressable></View></View>
    <View style={styles.section}><View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Recent updates</Text><Pressable onPress={onNotifications}><Text style={styles.seeAll}>View all</Text></Pressable></View>{summary.recentNotifications.length ? <Card style={styles.notificationCard}>{summary.recentNotifications.slice(0, 3).map((notification) => { const display = notificationPresentation(notification.type); return <NotificationRow icon={display.icon} key={notification.id} message={display.message} onPress={() => onOpenNotification(notification)} time={relativeNotificationTime(notification.createdAt)} tone={display.tone} />; })}</Card> : <View style={styles.emptyUpdates}><AppIcon color={colors.muted} name="notifications-off-outline" size={24} /><Text style={styles.emptyText}>Your latest ticket updates will appear here.</Text></View>}</View>
  </ScrollView></Shell>;
}

const styles = StyleSheet.create({
  splash: { alignItems: "center", backgroundColor: colors.hero, flex: 1, gap: 28, justifyContent: "center", overflow: "hidden" }, splashGlow: { backgroundColor: colors.heroAlt, borderRadius: 220, height: 440, position: "absolute", right: -200, top: -120, width: 440 }, splashCopy: { color: colors.heroMuted, fontSize: 15, letterSpacing: 1 },
  welcome: { flexGrow: 1, gap: 28, justifyContent: "space-between", padding: 24, paddingBottom: 32, paddingTop: 28 }, welcomeTop: { gap: 40 }, welcomeArt: { alignItems: "center", height: 190, justifyContent: "center" }, cityCircle: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 70, height: 140, justifyContent: "center", width: 140 }, roadLine: { backgroundColor: colors.lime, borderRadius: 4, bottom: 16, height: 8, position: "absolute", transform: [{ rotate: "-8deg" }], width: 230 }, welcomeCopy: { gap: 13 }, welcomeTitle: { color: colors.ink, fontSize: 34, fontWeight: fontWeights.bold, letterSpacing: -1.5, lineHeight: 40 }, welcomeSubtitle: { color: colors.muted, fontSize: 16, lineHeight: 25 }, welcomeActions: { gap: 14 }, staffLink: { alignItems: "center", flexDirection: "row", gap: 7, justifyContent: "center", minHeight: 44 }, staffLinkText: { color: colors.muted, fontSize: 14, fontWeight: fontWeights.semibold }, secureNote: { color: colors.muted, fontSize: 11, textAlign: "center" },
  authContent: { flexGrow: 1, gap: 24, padding: 22, paddingBottom: 40, paddingTop: 24 }, authCard: { gap: 14 }, inputLabel: { color: colors.ink, fontSize: 13, fontWeight: fontWeights.semibold }, input: { backgroundColor: colors.surfaceAlt, borderColor: colors.border, borderRadius: 14, borderWidth: 1, color: colors.ink, fontSize: 16, minHeight: 52, paddingHorizontal: 16 }, otpInput: { fontSize: 24, letterSpacing: 8, textAlign: "center" }, error: { color: colors.danger, fontSize: 14, lineHeight: 20 }, privacy: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center" },
  homeContent: { gap: 20, padding: 18, paddingBottom: 34, paddingTop: 18 }, homeHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, greeting: { color: colors.muted, fontSize: 11, marginLeft: 53, marginTop: 2 }, headerActions: { alignItems: "center", flexDirection: "row", gap: 9 }, iconButton: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 22, borderWidth: 1, height: 44, justifyContent: "center", width: 44 }, avatar: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 22, height: 44, justifyContent: "center", width: 44 }, badge: { alignItems: "center", backgroundColor: colors.danger, borderColor: colors.surface, borderRadius: 9, borderWidth: 1.5, minHeight: 18, justifyContent: "center", minWidth: 18, position: "absolute", right: -3, top: -4 }, badgeText: { color: colors.surface, fontSize: 9, fontWeight: fontWeights.bold },
  hero: { backgroundColor: colors.hero, borderRadius: 25, gap: 12, overflow: "hidden", padding: 22 }, heroGlow: { backgroundColor: colors.heroAlt, borderRadius: 140, height: 220, position: "absolute", right: -90, top: -85, width: 220 }, heroEyebrow: { color: colors.lime, fontSize: 11, fontWeight: fontWeights.bold, letterSpacing: 1.2 }, heroTitle: { color: colors.surface, fontSize: 27, fontWeight: fontWeights.bold, letterSpacing: -0.8 }, heroBody: { color: colors.heroMuted, fontSize: 14, lineHeight: 21, maxWidth: "90%" }, heroButton: { alignItems: "center", alignSelf: "flex-start", backgroundColor: colors.lime, borderRadius: 14, flexDirection: "row", gap: 9, marginTop: 7, minHeight: 48, paddingHorizontal: 15 }, heroButtonText: { color: colors.hero, fontSize: 15, fontWeight: fontWeights.bold },
  journeyCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.card, borderWidth: 1, gap: 13, padding: 15 }, sectionKicker: { color: colors.primary, fontSize: 10, fontWeight: fontWeights.bold, letterSpacing: 1 }, journey: { flexDirection: "row" }, journeyItem: { alignItems: "center", flex: 1, gap: 5 }, journeyIcon: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 18, height: 36, justifyContent: "center", width: 36 }, journeyLabel: { color: colors.muted, fontSize: 9, lineHeight: 12, textAlign: "center" }, journeyLine: { backgroundColor: colors.border, height: 1, left: "70%", position: "absolute", top: 18, width: "60%" },
  section: { gap: 11 }, sectionHeading: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, sectionTitle: { color: colors.ink, fontSize: typeScale.section, fontWeight: fontWeights.bold, letterSpacing: -0.4 }, sectionSubtitle: { color: colors.muted, fontSize: 12, marginTop: 2 }, countChip: { alignItems: "center", backgroundColor: colors.dangerBg, borderRadius: 12, justifyContent: "center", minHeight: 24, minWidth: 24 }, countChipText: { color: colors.danger, fontSize: 12, fontWeight: fontWeights.bold }, attentionCard: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 17, borderWidth: 1, flexDirection: "row", gap: 12, minHeight: 74, padding: 13 }, taskIcon: { alignItems: "center", backgroundColor: colors.infoBg, borderRadius: 20, height: 40, justifyContent: "center", width: 40 }, taskIconWarning: { backgroundColor: colors.warningBg }, taskCopy: { flex: 1, gap: 3 }, taskTitle: { color: colors.ink, fontSize: 15, fontWeight: fontWeights.semibold }, taskSubtitle: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  communityCard: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 19, flexDirection: "row", gap: 13, minHeight: 88, padding: 15 }, communityIcon: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 24, height: 48, justifyContent: "center", width: 48 }, reportStats: { flexDirection: "row", gap: 11 }, reportStat: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 18, borderWidth: 1, flex: 1, gap: 5, minHeight: 126, padding: 15 }, reportStatTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, reportCount: { color: colors.ink, fontSize: 25, fontWeight: fontWeights.bold }, reportLabel: { color: colors.ink, fontSize: 15, fontWeight: fontWeights.semibold }, reportHint: { color: colors.muted, fontSize: 11 }, seeAll: { color: colors.primary, fontSize: 12, fontWeight: fontWeights.semibold }, notificationCard: { gap: 0, overflow: "hidden", padding: 0 }, emptyUpdates: { alignItems: "center", backgroundColor: colors.surface, borderRadius: 17, flexDirection: "row", gap: 10, padding: 18 }, emptyText: { color: colors.muted, flex: 1, fontSize: 13 },
});
