import { useState } from "react";
import type { CitizenGrievanceReason, CitizenTicketDetail, CitizenTicketSummary, CitizenTicketTimelineResponse } from "@civicos/shared";
import * as ImagePicker from "expo-image-picker";
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { LocalImage } from "./api";
import { AppIcon, Card, PrimaryButton, ScreenHeader, SecondaryButton, StatusChip, TicketCard } from "./components";
import { normalizeAsset } from "./report-screens";
import { Shell } from "./screen-shell";
import { colors, fontWeights, radii, typeScale } from "./theme";

function daysLabel(deadline: string | Date): string {
  const days = Math.ceil((new Date(deadline).getTime() - Date.now()) / 86_400_000);
  if (days < 0) return `${Math.abs(days)} ${Math.abs(days) === 1 ? "day" : "days"} overdue`;
  if (days === 0) return "Due today";
  return `${days} ${days === 1 ? "day" : "days"} remaining`;
}

export function TicketsScreen({ filter, tickets, loading, error, onBack, onFilterChange, onOpen }: { filter: "ongoing" | "past"; tickets: CitizenTicketSummary[]; loading: boolean; error?: string; onBack: () => void; onFilterChange: (filter: "ongoing" | "past") => void; onOpen: (ticket: CitizenTicketSummary) => void }) {
  return <Shell><View style={styles.listScreen}><ScreenHeader eyebrow="My reports" title="Track your civic reports" subtitle="Follow ongoing work or revisit resolved issues." onBack={onBack} /><View style={styles.tabs}>{(["ongoing", "past"] as const).map((item) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: filter === item }} key={item} onPress={() => onFilterChange(item)} style={[styles.tab, filter === item && styles.tabActive]}><Text style={[styles.tabText, filter === item && styles.tabTextActive]}>{item === "ongoing" ? "Ongoing" : "Resolved"}</Text></Pressable>)}</View>{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<FlatList contentContainerStyle={styles.list} data={tickets} keyExtractor={(item) => item.id} ListEmptyComponent={!loading ? <View style={styles.empty}><AppIcon color={colors.muted} name="document-text-outline" size={32} /><Text style={styles.emptyTitle}>No {filter === "ongoing" ? "ongoing" : "resolved"} reports</Text><Text style={styles.body}>Reports in this category will appear here.</Text></View> : null} renderItem={({ item }) => <TicketCard id={item.id} referenceNumber={item.referenceNumber} category={item.category.name} status={item.statusLabel} relativeDate={new Date(item.updatedAt).toLocaleDateString("en-IN")} title={item.title} meta={item.address} onPress={() => onOpen(item)} />} /></View></Shell>;
}

export function TicketDetailScreen({ ticket, timeline, loading, error, onRefresh, onDone, onRaiseGrievance }: { ticket: CitizenTicketDetail; timeline?: CitizenTicketTimelineResponse; loading: boolean; error?: string; onRefresh: () => void; onDone: () => void; onRaiseGrievance: () => void }) {
  const evidence = ticket.originalEvidence[0];
  const completion = ticket.project?.completionEvidence[0];
  return <Shell><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={onRefresh} tintColor={colors.primary} />}><ScreenHeader eyebrow={`Ticket ${ticket.referenceNumber}`} title={ticket.title} subtitle={ticket.address} onBack={onDone} />{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.statusRow}><StatusChip label={ticket.statusLabel} />{ticket.responseDeadline ? <Text style={styles.deadline}>{daysLabel(ticket.responseDeadline)}</Text> : null}</View>{evidence ? <View style={styles.heroEvidence}><Image source={{ uri: evidence.url }} style={styles.photo} /><View style={styles.evidenceLabel}><Text style={styles.evidenceLabelText}>Original evidence</Text></View></View> : null}<Card><View style={styles.infoRow}><View style={styles.infoIcon}><AppIcon color={colors.primary} name="business-outline" size={21} /></View><View style={styles.infoCopy}><Text style={styles.infoLabel}>RESPONSIBLE AGENCY</Text><Text style={styles.infoValue}>{ticket.assignedAgency?.name ?? "Waiting for agency routing"}</Text></View></View><View style={styles.divider} /><View style={styles.infoRow}><View style={styles.infoIcon}><AppIcon color={colors.primary} name="person-outline" size={21} /></View><View style={styles.infoCopy}><Text style={styles.infoLabel}>CURRENT WORKFLOW</Text><Text style={styles.infoValue}>{ticket.project?.stateLabel ?? (ticket.assignedAgency ? "Project Head reviewing" : "Community validation")}</Text>{ticket.project?.engineerAssigned ? <Text style={styles.infoHint}>Executive Engineer assigned</Text> : null}</View></View>{ticket.project?.plannedEnd ? <><View style={styles.divider} /><View style={styles.infoRow}><View style={styles.infoIcon}><AppIcon color={colors.primary} name="calendar-outline" size={21} /></View><View style={styles.infoCopy}><Text style={styles.infoLabel}>TARGET DATE</Text><Text style={styles.infoValue}>{new Date(ticket.project.plannedEnd).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</Text></View></View></> : null}</Card>
    <View style={styles.section}><Text style={styles.sectionTitle}>Resolution journey</Text><Text style={styles.sectionSubtitle}>Completed and current stages are highlighted.</Text><Card style={styles.timelineCard}>{(timeline?.lifecycle ?? []).map((stage, index) => <View key={stage.id} style={styles.timelineRow}><View style={styles.timelineRail}><View style={[styles.timelineDot, stage.state === "complete" && styles.timelineDotComplete, stage.state === "current" && styles.timelineDotCurrent]}>{stage.state === "complete" ? <AppIcon color={colors.surface} name="checkmark" size={12} /> : null}</View>{index < (timeline?.lifecycle.length ?? 0) - 1 ? <View style={[styles.timelineLine, stage.state === "complete" && styles.timelineLineComplete]} /> : null}</View><View style={styles.timelineCopy}><Text style={[styles.timelineTitle, stage.state === "upcoming" && styles.timelineUpcoming, stage.state === "current" && styles.timelineCurrent]}>{stage.label}</Text>{stage.state === "current" ? <Text style={styles.currentLabel}>Current stage</Text> : stage.at ? <Text style={styles.timelineDate}>{new Date(stage.at).toLocaleDateString("en-IN")}</Text> : null}</View></View>)}</Card></View>
    {ticket.project?.dependencies.length ? <View style={styles.section}><Text style={styles.sectionTitle}>Agency coordination</Text>{ticket.project.dependencies.map((dependency) => <Card key={dependency.id}><View style={styles.dependencyRow}><View style={styles.infoCopy}><Text style={styles.infoValue}>{dependency.agencyName}</Text><Text style={styles.infoHint}>{dependency.statusLabel}</Text></View><StatusChip label={dependency.statusLabel} /></View></Card>)}</View> : null}
    {timeline?.notes.length ? <View style={styles.section}><Text style={styles.sectionTitle}>Updates from the team</Text>{timeline.notes.map((note) => <Card key={note.id}><Text style={styles.infoLabel}>{note.label}</Text><Text style={styles.noteText}>{note.text}</Text><Text style={styles.timelineDate}>{new Date(note.at).toLocaleString("en-IN")}</Text></Card>)}</View> : null}
    {completion ? <View style={styles.section}><Text style={styles.sectionTitle}>Completion evidence</Text><Card style={styles.completionCard}><Image source={{ uri: completion.photoUrl }} style={styles.completionPhoto} /><View style={styles.completionCopy}><Text style={styles.noteText}>{completion.notes}</Text><Text style={styles.timelineDate}>Submitted {new Date(completion.submittedAt).toLocaleDateString("en-IN")}</Text></View></Card></View> : null}
    {timeline?.grievances.length ? <View style={styles.section}><Text style={styles.sectionTitle}>City Connect grievance escalation</Text>{timeline.grievances.map((grievance) => <Card key={grievance.id}><View style={styles.dependencyRow}><Text style={styles.infoValue}>{grievance.reason.replaceAll("_", " ").toLowerCase()}</Text><StatusChip label={grievance.status} /></View><Text style={styles.infoHint}>Created {new Date(grievance.createdAt).toLocaleDateString("en-IN")}</Text>{grievance.resolutionNote ? <Text style={styles.noteText}>{grievance.resolutionNote}</Text> : null}</Card>)}</View> : null}
    {timeline?.canRaiseGrievance ? <SecondaryButton icon="alert-circle-outline" onPress={onRaiseGrievance}>Raise a grievance</SecondaryButton> : null}<PrimaryButton onPress={onDone}>Back to My Reports</PrimaryButton></ScrollView></Shell>;
}

const grievanceReasons: Array<{ value: CitizenGrievanceReason; label: string; detail: string }> = [
  { value: "ISSUE_UNRESOLVED", label: "Issue not resolved", detail: "The original problem is still present" },
  { value: "WORK_INCOMPLETE", label: "Incomplete work", detail: "Only part of the required work was done" },
  { value: "INCORRECT_CLOSURE", label: "Incorrect closure", detail: "The ticket should not have been closed" },
  { value: "POOR_EXECUTION_QUALITY", label: "Poor-quality execution", detail: "The completed work does not meet expectations" },
  { value: "OTHER", label: "Other", detail: "Tell us what needs further attention" },
];

export function GrievanceScreen({ submitting, onBack, onSubmit }: { submitting: boolean; onBack: () => void; onSubmit: (reason: CitizenGrievanceReason, note?: string, evidence?: LocalImage) => void }) {
  const [reason, setReason] = useState<CitizenGrievanceReason>("ISSUE_UNRESOLVED");
  const [note, setNote] = useState("");
  const [evidence, setEvidence] = useState<LocalImage>();
  const pickEvidence = async () => {
    const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) return;
    const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.85 });
    if (!result.canceled && result.assets[0]) setEvidence(normalizeAsset(result.assets[0]));
  };
  return <Shell><ScrollView contentContainerStyle={styles.content}><ScreenHeader eyebrow="City Connect grievance escalation" title="Tell us what remains wrong" subtitle="Your grievance stays linked to the original ticket and is sent to the responsible authority." onBack={onBack} /><View accessibilityRole="radiogroup" style={styles.reasonList}>{grievanceReasons.map((item) => { const selected = reason === item.value; return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} key={item.value} onPress={() => setReason(item.value)} style={[styles.reasonCard, selected && styles.reasonCardSelected]}><View style={[styles.radio, selected && styles.radioSelected]}>{selected ? <View style={styles.radioInner} /> : null}</View><View style={styles.infoCopy}><Text style={styles.reasonTitle}>{item.label}</Text><Text style={styles.infoHint}>{item.detail}</Text></View></Pressable>; })}</View><Text style={styles.inputLabel}>Additional note</Text><TextInput accessibilityLabel="Optional grievance note" multiline onChangeText={setNote} placeholder="Describe what is still wrong" placeholderTextColor={colors.muted} style={[styles.input, styles.textarea]} value={note} /><SecondaryButton icon="image-outline" onPress={() => void pickEvidence()}>{evidence ? "Change evidence photo" : "Add evidence photo (optional)"}</SecondaryButton>{evidence ? <Image source={{ uri: evidence.uri }} style={styles.grievancePhoto} /> : null}<View style={styles.grievanceNotice}><AppIcon color={colors.infoText} name="information-circle-outline" size={20} /><Text style={styles.grievanceNoticeText}>This is a City Connect grievance workflow. It does not claim direct integration with a government grievance platform.</Text></View><PrimaryButton disabled={submitting} icon="send" onPress={() => onSubmit(reason, note.trim() || undefined, evidence)}>{submitting ? "Submitting…" : "Submit grievance"}</PrimaryButton></ScrollView></Shell>;
}

const styles = StyleSheet.create({
  listScreen: { flex: 1, gap: 15, padding: 20, paddingBottom: 0, paddingTop: 22 }, tabs: { backgroundColor: colors.surfaceAlt, borderRadius: 14, flexDirection: "row", padding: 4 }, tab: { alignItems: "center", borderRadius: 11, flex: 1, minHeight: 42, justifyContent: "center" }, tabActive: { backgroundColor: colors.surface }, tabText: { color: colors.muted, fontSize: 14, fontWeight: fontWeights.semibold }, tabTextActive: { color: colors.primary }, list: { gap: 12, paddingBottom: 30 }, empty: { alignItems: "center", gap: 9, padding: 45 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: fontWeights.bold },
  content: { flexGrow: 1, gap: 18, padding: 20, paddingBottom: 36, paddingTop: 22 }, error: { color: colors.danger, fontSize: 14, lineHeight: 20 }, body: { color: colors.muted, fontSize: 14, lineHeight: 21 }, statusRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, deadline: { color: colors.warningText, fontSize: 12, fontWeight: fontWeights.semibold }, heroEvidence: { borderRadius: radii.card, height: 240, overflow: "hidden" }, photo: { height: "100%", width: "100%" }, evidenceLabel: { backgroundColor: colors.overlay, borderRadius: 10, bottom: 12, left: 12, paddingHorizontal: 10, paddingVertical: 6, position: "absolute" }, evidenceLabelText: { color: colors.surface, fontSize: 11, fontWeight: fontWeights.semibold },
  infoRow: { alignItems: "flex-start", flexDirection: "row", gap: 12 }, infoIcon: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 20, height: 40, justifyContent: "center", width: 40 }, infoCopy: { flex: 1, gap: 3 }, infoLabel: { color: colors.muted, fontSize: 10, fontWeight: fontWeights.bold, letterSpacing: 0.8 }, infoValue: { color: colors.ink, fontSize: 15, fontWeight: fontWeights.semibold, lineHeight: 21 }, infoHint: { color: colors.muted, fontSize: 12, lineHeight: 17 }, divider: { backgroundColor: colors.border, height: 1 }, section: { gap: 10 }, sectionTitle: { color: colors.ink, fontSize: typeScale.section, fontWeight: fontWeights.bold }, sectionSubtitle: { color: colors.muted, fontSize: 12 },
  timelineCard: { gap: 0 }, timelineRow: { flexDirection: "row", minHeight: 58 }, timelineRail: { alignItems: "center", width: 28 }, timelineDot: { backgroundColor: colors.border, borderRadius: 11, height: 22, width: 22, zIndex: 2 }, timelineDotComplete: { alignItems: "center", backgroundColor: colors.primary, justifyContent: "center" }, timelineDotCurrent: { backgroundColor: colors.lime, borderColor: colors.primary, borderWidth: 5 }, timelineLine: { backgroundColor: colors.border, flex: 1, width: 2 }, timelineLineComplete: { backgroundColor: colors.primary }, timelineCopy: { flex: 1, gap: 2, paddingBottom: 13, paddingLeft: 10 }, timelineTitle: { color: colors.ink, fontSize: 14, fontWeight: fontWeights.semibold }, timelineUpcoming: { color: colors.muted, fontWeight: fontWeights.regular }, timelineCurrent: { color: colors.primary }, currentLabel: { color: colors.primary, fontSize: 11, fontWeight: fontWeights.semibold }, timelineDate: { color: colors.muted, fontSize: 11 }, dependencyRow: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "space-between" }, noteText: { color: colors.ink, fontSize: 14, lineHeight: 21 }, completionCard: { overflow: "hidden", padding: 0 }, completionPhoto: { height: 220, width: "100%" }, completionCopy: { gap: 6, padding: 16 },
  reasonList: { gap: 9 }, reasonCard: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 11, minHeight: 70, padding: 13 }, reasonCardSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, radio: { borderColor: colors.border, borderRadius: 10, borderWidth: 2, height: 20, width: 20, alignItems: "center", justifyContent: "center" }, radioSelected: { borderColor: colors.primary }, radioInner: { backgroundColor: colors.primary, borderRadius: 5, height: 10, width: 10 }, reasonTitle: { color: colors.ink, fontSize: 14, fontWeight: fontWeights.semibold }, inputLabel: { color: colors.ink, fontSize: 13, fontWeight: fontWeights.semibold }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, color: colors.ink, fontSize: 15, paddingHorizontal: 14, paddingVertical: 12 }, textarea: { minHeight: 105, textAlignVertical: "top" }, grievancePhoto: { borderRadius: radii.card, height: 220, width: "100%" }, grievanceNotice: { alignItems: "flex-start", backgroundColor: colors.infoBg, borderRadius: 14, flexDirection: "row", gap: 9, padding: 13 }, grievanceNoticeText: { color: colors.infoText, flex: 1, fontSize: 11, lineHeight: 17 },
});
