import type { CompletionVerificationDecision, PendingCompletionVerification, PendingValidation, ValidationVote } from "@civicos/shared";
import { ActivityIndicator, FlatList, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppIcon, Card, PrimaryButton, ScreenHeader, SecondaryButton } from "./components";
import { Shell } from "./screen-shell";
import { colors, fontWeights, radii, typeScale } from "./theme";

function relativeReportedTime(value: string | Date): string {
  const minutes = Math.max(1, Math.floor((Date.now() - new Date(value).getTime()) / 60_000));
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

export function VerificationListScreen({ validations, loading, error, onBack, onOpen }: { validations: PendingValidation[]; loading: boolean; error?: string; onBack: () => void; onOpen: (validation: PendingValidation) => void }) {
  return <Shell><View style={styles.screen}><ScreenHeader eyebrow="Community validation" title="Help confirm reported issues" subtitle="Your response helps genuine civic reports reach the right agency." onBack={onBack} />{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<FlatList contentContainerStyle={styles.list} data={validations} keyExtractor={(item) => item.ticketId} ListEmptyComponent={!loading ? <View style={styles.empty}><View style={styles.emptyIcon}><AppIcon color={colors.primary} name="checkmark-done" size={30} /></View><Text style={styles.emptyTitle}>You’re all caught up</Text><Text style={styles.body}>No community validation requests need your help right now.</Text></View> : null} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => onOpen(item)} style={styles.requestCard}><Image source={{ uri: item.imageUrl }} style={styles.cardImage} /><View style={styles.cardBody}><View style={styles.cardTop}><Text style={styles.kicker}>{item.category.name}</Text><Text style={styles.time}>{relativeReportedTime(item.reportedAt)}</Text></View><Text numberOfLines={2} style={styles.cardTitle}>{item.title}</Text><View style={styles.locationRow}><AppIcon color={colors.muted} name="location-outline" size={15} /><Text numberOfLines={2} style={styles.location}>{item.address}</Text></View><View style={styles.progressRow}><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${Math.min(100, (item.confirmationCount / item.quorum) * 100)}%` }]} /></View><Text style={styles.progressText}>{item.confirmationCount} of {item.quorum} confirmed</Text></View></View></Pressable>} /></View></Shell>;
}

export function VerificationRequestScreen({ validation, submitting, onBack, onSubmit }: { validation: PendingValidation; submitting: boolean; onBack: () => void; onSubmit: (vote: ValidationVote) => void }) {
  return <Shell><ScrollView contentContainerStyle={styles.content}><ScreenHeader eyebrow="Community validation" title="Does this issue appear genuine?" subtitle="Help confirm whether this issue appears genuine." onBack={onBack} /><View style={styles.largeImage}><Image source={{ uri: validation.imageUrl }} style={styles.photo} /></View><Card><View style={styles.cardTop}><Text style={styles.kicker}>{validation.category.name}</Text><Text style={styles.time}>{relativeReportedTime(validation.reportedAt)}</Text></View><Text style={styles.detailTitle}>{validation.title}</Text><View style={styles.locationRow}><AppIcon color={colors.primary} name="location" size={18} /><Text style={styles.location}>{validation.address}</Text></View><View style={styles.confirmationBox}><AppIcon color={colors.infoText} name="people-outline" size={20} /><Text style={styles.confirmationText}>{validation.confirmationCount} of {validation.quorum} citizens confirmed</Text></View></Card><Text style={styles.guidance}>Review the photo and location. Choose the response that best matches what you can verify.</Text><PrimaryButton disabled={submitting} icon="checkmark-circle" onPress={() => onSubmit("CONFIRM")}>{submitting ? "Recording…" : "Confirm"}</PrimaryButton><SecondaryButton disabled={submitting} icon="close-circle-outline" onPress={() => onSubmit("REJECT")}>Reject</SecondaryButton><Pressable accessibilityRole="button" disabled={submitting} onPress={() => onSubmit("NOT_SURE")} style={styles.notSure}><Text style={styles.notSureText}>I’m not sure</Text></Pressable></ScrollView></Shell>;
}

export function CompletionVerificationListScreen({ completions, loading, error, onBack, onOpen }: { completions: PendingCompletionVerification[]; loading: boolean; error?: string; onBack: () => void; onOpen: (completion: PendingCompletionVerification) => void }) {
  return <Shell><View style={styles.screen}><ScreenHeader eyebrow="Completion verification" title="Work awaiting your check" subtitle="Review completed work connected to reports you helped validate." onBack={onBack} />{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<FlatList contentContainerStyle={styles.list} data={completions} keyExtractor={(item) => item.evidenceId} ListEmptyComponent={!loading ? <View style={styles.empty}><View style={styles.emptyIcon}><AppIcon color={colors.primary} name="checkmark-circle-outline" size={31} /></View><Text style={styles.emptyTitle}>No completion checks</Text><Text style={styles.body}>Completed work requiring your review will appear here.</Text></View> : null} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => onOpen(item)} style={styles.requestCard}><Image source={{ uri: item.photoUrl }} style={styles.cardImage} /><View style={styles.cardBody}><Text style={styles.kicker}>{item.categoryName}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.location}>{item.address}</Text><Text style={styles.time}>Completed {new Date(item.submittedAt).toLocaleDateString("en-IN")}</Text></View></Pressable>} /></View></Shell>;
}

export function CompletionVerificationScreen({ completion, submitting, onBack, onSubmit }: { completion: PendingCompletionVerification; submitting: boolean; onBack: () => void; onSubmit: (decision: CompletionVerificationDecision) => void }) {
  return <Shell><ScrollView contentContainerStyle={styles.content}><ScreenHeader eyebrow="Completion verification" title="Has the issue been resolved?" subtitle="Compare the original report with the completed work." onBack={onBack} /><Text style={styles.sectionTitle}>Before</Text>{completion.originalPhotoUrl ? <Image source={{ uri: completion.originalPhotoUrl }} style={styles.compareImage} /> : <Card><Text style={styles.body}>Original evidence is unavailable.</Text></Card>}<Text style={styles.sectionTitle}>After</Text><Image source={{ uri: completion.photoUrl }} style={styles.compareImage} /><Card><Text style={styles.detailTitle}>{completion.title}</Text><View style={styles.metaLine}><AppIcon color={colors.primary} name="business-outline" size={18} /><Text style={styles.metaText}>{completion.agencyName}</Text></View>{completion.engineerLabel ? <View style={styles.metaLine}><AppIcon color={colors.primary} name="person-outline" size={18} /><Text style={styles.metaText}>{completion.engineerLabel}</Text></View> : null}<View style={styles.metaLine}><AppIcon color={colors.primary} name="calendar-outline" size={18} /><Text style={styles.metaText}>{new Date(completion.submittedAt).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</Text></View><View style={styles.noteBox}><Text style={styles.noteLabel}>Completion note</Text><Text style={styles.noteText}>{completion.notes}</Text></View></Card><PrimaryButton disabled={submitting} icon="checkmark-circle" onPress={() => onSubmit("VERIFIED")}>Confirm resolved</PrimaryButton><SecondaryButton disabled={submitting} icon="alert-circle-outline" onPress={() => onSubmit("REWORK_REQUESTED")}>Still not resolved</SecondaryButton><Text style={styles.guidance}>Selecting “Still not resolved” requests rework. The original reporter can also open a City Connect grievance from the ticket.</Text></ScrollView></Shell>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, gap: 15, padding: 20, paddingBottom: 0, paddingTop: 22 }, content: { flexGrow: 1, gap: 17, padding: 20, paddingBottom: 36, paddingTop: 22 }, list: { gap: 14, paddingBottom: 30 }, error: { color: colors.danger, fontSize: 14 }, requestCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.card, borderWidth: 1, elevation: 1, overflow: "hidden", shadowColor: colors.hero, shadowOffset: { height: 3, width: 0 }, shadowOpacity: 0.05, shadowRadius: 10 }, cardImage: { aspectRatio: 16 / 9, maxHeight: 155, width: "100%" }, cardBody: { gap: 8, padding: 15 }, cardTop: { flexDirection: "row", flexWrap: "wrap", gap: 6, justifyContent: "space-between" }, kicker: { color: colors.primary, fontSize: 10, fontWeight: fontWeights.bold, letterSpacing: 0.8, textTransform: "uppercase" }, time: { color: colors.muted, fontSize: 11 }, cardTitle: { color: colors.ink, fontSize: 16, fontWeight: fontWeights.semibold, lineHeight: 22 }, locationRow: { alignItems: "flex-start", flexDirection: "row", gap: 5 }, location: { color: colors.muted, flex: 1, fontSize: 12, lineHeight: 17 }, progressRow: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 3 }, progressTrack: { backgroundColor: colors.border, borderRadius: 3, flex: 1, height: 5, overflow: "hidden" }, progressFill: { backgroundColor: colors.primary, height: 5 }, progressText: { color: colors.primary, fontSize: 11, fontWeight: fontWeights.semibold }, empty: { alignItems: "center", gap: 9, padding: 45 }, emptyIcon: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 32, height: 64, justifyContent: "center", width: 64 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: fontWeights.bold }, body: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: "center" },
  largeImage: { aspectRatio: 4 / 3, borderRadius: radii.card, maxHeight: 320, overflow: "hidden", width: "100%" }, photo: { height: "100%", width: "100%" }, detailTitle: { color: colors.ink, fontSize: 18, fontWeight: fontWeights.bold, lineHeight: 25 }, confirmationBox: { alignItems: "center", backgroundColor: colors.infoBg, borderRadius: 13, flexDirection: "row", flexWrap: "wrap", gap: 8, padding: 11 }, confirmationText: { color: colors.infoText, fontSize: 12, fontWeight: fontWeights.semibold }, guidance: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center" }, notSure: { alignItems: "center", minHeight: 44, justifyContent: "center" }, notSureText: { color: colors.muted, fontSize: 14, fontWeight: fontWeights.semibold }, sectionTitle: { color: colors.ink, fontSize: typeScale.section, fontWeight: fontWeights.bold }, compareImage: { aspectRatio: 4 / 3, borderRadius: radii.card, maxHeight: 235, width: "100%" }, metaLine: { alignItems: "center", flexDirection: "row", gap: 8 }, metaText: { color: colors.muted, fontSize: 13 }, noteBox: { backgroundColor: colors.surfaceAlt, borderRadius: 13, gap: 5, marginTop: 5, padding: 12 }, noteLabel: { color: colors.primary, fontSize: 10, fontWeight: fontWeights.bold, letterSpacing: 0.7, textTransform: "uppercase" }, noteText: { color: colors.ink, fontSize: 14, lineHeight: 21 },
});
